// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.Plybot2020.subsystems;


import org.usfirst.frc2619.Plybot2020.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;

import com.ctre.phoenix.motorcontrol.ControlMode;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX shooterMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private static final double SPEED_P_CONSTANT = 0; //for now
    private static final double SPEED_I_CONSTANT = 0; 
    private static final double SPEED_D_CONSTANT = 0;
    private static final double SPEED_F_CONSTANT = 0;
    private boolean isRunningOut = true;
    private boolean isRunningIn = false;
    public Shooter() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shooterMotor = new WPI_TalonSRX(7);
        
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void stop()
    {
        shooterMotor.set(0);
    }

    public void run(double power) //power mode
    {
        shooterMotor.set(ControlMode.PercentOutput, power);
    }

    public void initSpeedMode() //initalizes
    {
        shooterMotor.set(ControlMode.Velocity, 0);

        //Assigned PID constants to the motors
        shooterMotor.config_kP(1, SPEED_P_CONSTANT);
        shooterMotor.config_kI(1, SPEED_I_CONSTANT);
        shooterMotor.config_kD(1, SPEED_D_CONSTANT);
        shooterMotor.config_kF(1, SPEED_F_CONSTANT);

        //Don't know what this is yet
        shooterMotor.selectProfileSlot(1, 0);   //1 box, 0th slot
    }

    public void setPercentSpeedPID(double speed)
    {
        shooterMotor.set(ControlMode.Velocity, speed);
    } //sets speed (speed mode)

    public boolean isRunningOut(double speed)
    {
        if(speed > 0)
        {
            return isRunningOut;
        }
        else
        {
            return isRunningIn;
        }
    } //returns true or false for other susbsystems to use
}

